// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8G3AJaGOpSczVah8PAatyS3zuy1kLUUE',
    appId: '1:864157729046:web:790bde17ea92b8f53e5037',
    messagingSenderId: '864157729046',
    projectId: 'flutter-todo-app-8dc15',
    authDomain: 'flutter-todo-app-8dc15.firebaseapp.com',
    storageBucket: 'flutter-todo-app-8dc15.firebasestorage.app',
    measurementId: 'G-MTNHLP2828',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_sARSNqwAAxm1CqGhEcHRXRfmXcvJH0',
    appId: '1:864157729046:android:21ef6055eada3aa73e5037',
    messagingSenderId: '864157729046',
    projectId: 'flutter-todo-app-8dc15',
    storageBucket: 'flutter-todo-app-8dc15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzttP5b2TrfDvUL3Ll4_AwCzvQlYrU7rI',
    appId: '1:864157729046:ios:b8eb19abff26c2e43e5037',
    messagingSenderId: '864157729046',
    projectId: 'flutter-todo-app-8dc15',
    storageBucket: 'flutter-todo-app-8dc15.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
